version: '2'
services:
  drupal-lamp:
    build: apache
#    image: comicrelief/drupal:0.0.23
    ports:
      - 8080:80
    depends_on:
      - mysql
      - memcached
      - rabbitmq
#      - solr
    volumes:
      - ./www:/var/www
    working_dir: /var/www
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: drupal
    ports:
      - 3307:3306
  memcached:
    image: memcached
    expose:
      - 11211
    ports:
      - 11211:11211
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    hostname: drupal-rabbit
    environment:
      RABBITMQ_HIPE_COMPILE: 1
#  solr:
#    image: solr:5.4.1
#    ports:
#      - 8983:8983
#    volumes:
#      - ./www/profiles/cr/modules/contrib/search_api_solr/solr-conf/5.x:/drupal/conf
#    entrypoint:
#      - docker-entrypoint.sh
#      - solr-precreate
#      - rnd17
#      - /drupal
