version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: local_drupal
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3306"
  web:
    depends_on:
      - mysql
    build: apache
    volumes:
      - ./www:/var/www
    links:
      - mysql
    ports:
      - "8080:80"
    working_dir: /var/www
  solr:
    image: makuk66/docker-solr:5.3
    volumes:
      - ./solr/solr.xml:/opt/solr/example/solr/solr.xml
      - ../campaign/profiles/cr/modules/contrib/search_api_solr/solr-conf/5.x:/opt/solr/server/solr/drupal/conf
    ports:
      - "8983:8983"
#  rabbitmq:
#    image: rabbitmq
